## PRIOR PREDICTIVE CHECK for the ex1 sigma_data multiple.
## Question: at what sigma_data can the STATIONARY (stat_weak) model's prior predictive reproduce the
## sd and RMS of data generated by the NONSTATIONARY model (the ex1 DGP)?
## Prediction under test: too-small sigma_data cannot reach the observed sd at all; a sigma_data large
## enough to match sd will OVERSHOOT rms on average, but should still cover the observed rms in a
## reasonable fraction of draws.
## Exact shortcut: with fit_scales = 0 the prior predictive is LINEAR in sigma_data
##   Y = sigma * [Lambda.Phi + tau*noise]
## so one simulation at sigma_data = 1 characterises every multiple by rescaling.
library(posterior)
source("../sample_model.r"); source("../pathfinder_init.r")
ife_mod <- cmdstan_model("../ife_named_cartesian.stan")
rms <- function(x) sqrt(mean(x^2))

GEN_K <- 4L; REPS <- 30L
set.seed(40318)                                   # same stream as ex1_sim_study
study_units <- sample.int(2 * REPS, size = REPS, replace = FALSE)
pp_seed <- sample.int(.Machine$integer.max, 1)

## (1) the "observed" data: nonstationary model prior predictive = the ex1 DGP
obs <- sample_model(overall_scales = rep(1, 8), err_scale = 3, alpha_diag = 10,
  autocor_a = 8, autocor_b = 2, nonstationary = TRUE, num_treated = 0, type = "prior_pred",
  K_latent = GEN_K, iter = 2 * REPS, seed = pp_seed)

## (2) the stationary (stat_weak) model's prior predictive at UNIT scale
stat1 <- sample_model(overall_scales = rep(1, 8), err_scale = 0, err_scale_mean = 0.1,
  err_scale_sd = 0.1, alpha_diag = 10, autocor_a = 97, autocor_b = 3, nonstationary = FALSE,
  num_treated = 0, type = "prior_pred", K_latent = GEN_K, iter = 1000, seed = 20260825)
# per-draw, per-unit shape statistics at sigma_data = 1
S1 <- as.numeric(apply(stat1$ys, c(1, 3), sd))      # [draws x units] -> vector
R1 <- as.numeric(apply(stat1$ys, c(1, 3), rms))
cat(sprintf("\nstat_weak prior predictive at sigma_data = 1 (n=%d unit-draws):\n", length(S1)))
cat(sprintf("  sd : med=%.3f  q05=%.3f q95=%.3f     RMS: med=%.3f q05=%.3f q95=%.3f\n\n",
  median(S1), quantile(S1,.05), quantile(S1,.95), median(R1), quantile(R1,.05), quantile(R1,.95)))

## (3) for each observed dataset and each multiple, can the prior predictive reach the observed sd/RMS?
## sigma_data = mult * RMS(y_obs), so simulated sd = sigma_data * S1 ; compare against observed sd.
cat("For each multiple: P(prior-predictive stat >= observed) -- ~0 means the check FAILS (cannot reach\n")
cat("the observed value); ~0.5 means centred; ~1 means systematic overshoot. 'cover' = observed lies\n")
cat("inside the central 90% of the prior predictive.\n\n")
mults <- c(1.0, 1.5, 2.0, 2.5, 3.0)
agg <- list()
for (ds in study_units[1:5]) {
  ys <- obs$ys[ds, , ]
  sd_o <- mean(apply(ys, 2, sd)); rms_o <- mean(apply(ys, 2, rms))
  for (m in mults) {
    sig <- m * rms_o
    p_sd  <- mean(sig * S1 >= sd_o);  cov_sd  <- (sd_o  >= quantile(sig*S1, .05)) && (sd_o  <= quantile(sig*S1, .95))
    p_rms <- mean(sig * R1 >= rms_o); cov_rms <- (rms_o >= quantile(sig*R1, .05)) && (rms_o <= quantile(sig*R1, .95))
    agg[[length(agg)+1]] <- data.frame(ds = ds, mult = m, P_sd = p_sd, cov_sd = cov_sd,
                                       P_rms = p_rms, cov_rms = cov_rms)
  }
}
A <- do.call(rbind, agg)
cat(sprintf("observed data: mean sd=%.2f  mean RMS=%.2f  (RMS/sd=%.2f)\n\n",
  mean(sapply(study_units[1:5], function(d) mean(apply(obs$ys[d,,],2,sd)))),
  mean(sapply(study_units[1:5], function(d) mean(apply(obs$ys[d,,],2,rms)))),
  mean(sapply(study_units[1:5], function(d) mean(apply(obs$ys[d,,],2,rms))/mean(apply(obs$ys[d,,],2,sd))))))
cat(sprintf("%-6s %-22s %-22s\n", "mult", "SD: P(pp>=obs) cover", "RMS: P(pp>=obs) cover"))
for (m in mults) { s <- A[A$mult == m, ]
  cat(sprintf("%-6.1f    %.3f        %d/5        %.3f        %d/5\n",
    m, mean(s$P_sd), sum(s$cov_sd), mean(s$P_rms), sum(s$cov_rms))) }
saveRDS(A, "/private/tmp/claude-502/-Users-collin-Documents-Wake-Research-PriorPredictivePaper-reprod/0edcfb95-808f-4867-8f30-15ec1e2aec59/scratchpad/ex1_ppc.rds")
cat("\nRead: the smallest multiple whose SD column is not ~0 (and ideally covers) is the prior-predictive\n")
cat("justification for the multiple; the RMS column shows the overshoot cost of getting there.\n")
